[client]
showSidebarNavigation = false

[theme]
primaryColor = "#1DB954"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#161b22"
textColor = "#f0f6fc"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
